### ISSUE TITLE
IAMR postprocessing bug?

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/IAMR#135]
Hey,

Can someone help to check this potential bug? A [three-minute short video](https://drive.google.com/file/d/1P6xsQoNfKYZD3ptKeDAUBkX8DrovLZbj/view?usp=sharing) is attached to reproduce this bug. 

It shows that we can not see the meshes and # of cells on the finest level in Paraview 5.10.1. I am guessing the bug is from the postprocessing part of IAMR.

Best.

**Comment by ruohai0925** [comment]
I also tested the Praview 5.11.1, the bug is still there.

**Comment by esclapez** [comment]
By default, Paraview will load the AMReX plotfile metadata for all the levels, but you control manually up to which level it will read the actual data. In your video, you only load the data up to Level 1, you have to increase up to level 2 in order to have your finest level (level 2). See the attached picture extracted from your video:

![Screen Shot 2023-07-03 at 4 58 27 PM](https://github.com/AMReX-Codes/IAMR/assets/13371051/54e2e233-aa29-4294-af29-a61c9b40a5aa)

**Comment by ruohai0925** [comment]
Thanks, Lucas!
